### ISSUE TITLE
Optionally Persist step state in url or localStorage

### ISSUE THREAD

**Issue by crobinson42** [jcmcneal/react-step-wizard#3]
Thoughts on adding feature for optional url hash of the step # or localStorage?

Very primitive initial thoughts:

```
<StepWizard persistSate="url">
    <Step><Step1 /></Step>
    <Step><Step2 /></Step>
    <Step><Step.. /></Step>
    <Step><Step..12 /></Step>
    <Step><WhateverComponentName /></Step>
  </StepWizard>
```

**Comment by jcmcneal** [comment]
I toyed with the idea of persisting the step in the url hash but you're right, it would have to be optional. 

We could take it a step further and give each step a name so instead of the url saying `#step2` it would be `#whateverYouDefine` and then pass a prop to the steps like
```
<StepWizard persistState="url">
   <Step name/hash='#whateverYouDefine'></Step>
</StepWizard>
```
Those are also my primitive thoughts. I appreciate the suggestions!

**Comment by jcmcneal** [comment]
This feature has been added in `v4.3.0`
