### ISSUE TITLE
How can I disable transitions ?

### ISSUE THREAD

**Issue by seloner** [jcmcneal/react-step-wizard#43]
How can I disable transitions ?

**Comment by mperlet** [comment]
Hi, you can use empty strings to disable transitions:
```
render() {
    let noTransitions = {
      enterRight: '',
      enterLeft: '',
      exitRight: '',
      exitLeft: ''
    };

    return (
 <StepWizard  transitions={noTransitions}>
  <Step1 />
  <Step2 />
</StepWizard>
)
}

**Comment by resolritter** [comment]
Setting it to empty strings is indeed the way to go, since transitions default to animations.

https://github.com/jcmcneal/react-step-wizard/blob/74267d480a917add1fba83dea79b83505c0ac0bd/src/index.js#L72-L77

I believe this is solved. If the current API is not satisfactory enough, I think another issue could be opened with improvement suggestions.
