### ISSUE TITLE
isHashEnabled sets #undefined

### ISSUE THREAD

**Issue by johisco** [jcmcneal/react-step-wizard#64]
Im experiencing some issues with the isHashEnable flag where it sets the router browser url to #undefined instead of #step1 ... #step{N} etc...

```
<StepWizard
                              isHashEnabled={true}
                              transitions={{
                                enterRight: "",
                                enterLeft: "",
                                exitRight: "",
                                exitLeft: "",
                              }}
                            >
                              {this.state.steps.map((stepdata, i) => {
                                return (
                                  <CustomStep
                                    key={i}
                                    data={stepdata}
                                    update={this.setData}
                                    canGoBack={this.canGoBack}
                                  />
                                );
                              })}
                            </StepWizard>
```

Im using `eact-router-dom` as my router if that matters... ?

**Comment by resolritter** [comment]
The hashKeys are computed upfront when the StepWizard component is constructed

https://github.com/jcmcneal/react-step-wizard/blob/17e80df5a716052c652c1c2651c6dded0a0096a0/src/index.js#L11

https://github.com/jcmcneal/react-step-wizard/blob/17e80df5a716052c652c1c2651c6dded0a0096a0/src/index.js#L43-L45

I suppose that could happen if your `this.state.steps` is changing after the first render, because the steps would probably no longer re-hashed, then. This is just a guess, though; I could look into fixing this you provide a minimal reproduction.

**Comment by resolritter** [comment]
Closing due to lack of response
