### ISSUE TITLE
n.props.children.forEach is not a function

### ISSUE THREAD

**Issue by RamonAcedoM** [jcmcneal/react-step-wizard#7]
Hi, i've been trying to use your example, but i can't get it to work, i've tried from a fresh react project, using the same setup (even babel 6 and babel loader 7) but it prompts out that error:

n.props.children.forEach is not a function.

Do you have any idea what could be wrong?

**Comment by jcmcneal** [comment]
Can you post an example of your code? It looks like it may be an issue with how the child components are setup.

**Comment by RamonAcedoM** [comment]
Hi, yeah:
App.js
```
import React, { Component } from 'react'
import StepWizard from 'react-step-wizard'

import SlideExperience from './SlideExperience'

export default class App extends Component {

    constructor(props){
        super(props);
    }

    render() {
        return(
            <div>
                <StepWizard>
                    <SlideExperience title="Slide 1"/>
                    <SlideExperience title="Slide 2" />
                </StepWizard>
            </div>
        )
    }
}
```
SlideExperience.js
```
import React, { Component } from 'react'

export default class SlideExperience extends Component{

    render(){
        return(
            <div>
                <div>TEXT EXPERIENCE {this.props.title}</div>
                <button onClick={this.props.previousStep}>PREVIOUS</button>
                <button onClick={this.props.nextStep}>NEXT</button>
            </div>
        )
    }

}
```
Weird enough if i downgrade it to 4.2.0 it just works.

**Comment by jcmcneal** [comment]
Is there a specific browser you're seeing this error in or is it all browsers?

**Comment by RamonAcedoM** [comment]
Well it has happened to me on Firefox, Chrome and Safari

Sorry for the late response.

**Comment by jcmcneal** [comment]
Using your snippets I am able to run it just fine on v4.3.1. Can't reproduce.

I can think of a few reasons why this `could` be happening:
1. The child props are not being transpiled as an array by React. (not sure if that can happen). `forEach` expects an array so that's why it would fail.
2. `forEach` is not supported by your browsers. I would expect that to only happen in IE. Not modern browsers like Chrome and Firefox. However, it works in IE for me and I'm not using a polyfill.
3. Your babel configuration needs adjusted. This seems like the most likely cause. Do you mind posting your babel config so I can take a look?

Those are the only likely causes that come to mind at the moment.

**Comment by jcmcneal** [comment]
@RamonAcedoM any update on this?

**Comment by RamonAcedoM** [comment]
@jcmcneal After a long time we came to the conclusion that we had a bad environment configuration. 

Everything is working fine on Chrome, Firefox and IE.

Great library!

**Comment by jcmcneal** [comment]
Thanks, I'm glad you figured out the problem! 👍
