### ISSUE TITLE
In the example, if you leave the automated step before it finishes by selecting another step, once the progress is finished it advances you one step despite the fact that you left the step.

### ISSUE THREAD

**Issue by dmartensson** [jcmcneal/react-step-wizard#9]
To reproduce, once the progress bar starts, go to first step and wait.

After at while you will automatically be moved to second step.

**Comment by jcmcneal** [comment]
You're right, I would need to add a `clearTimeout` method to that step to achieve expected behavior.

However, this is a bad implementation on my part rather than a bug with the `StepWizard` itself. I will update it when I get a chance so I'm providing good examples, but for now I'm going to close the issue. I will comment when I've updated the example.

**Comment by jcmcneal** [comment]
This has been fixed.
